### PR TITLE
Remove statefs require

### PR DESCRIPTION
**Pull request by neochapay**

### CODE REVIEW

**Comment by FlorentRevest** [comment]
Sorry for the very late review @neochapay, those were hectic times for me :)
I'm assuming this is just an upstream backport of https://git.sailfishos.org/mer-core/lipstick/commit/07798de03896eeda3a8ed8ce0cfb22df2a95e903 so I'll accept it.
What is your plan with this though? Do you plan to remove statefs from asteroid? (I'd be happy with this :) )

**Comment by FlorentRevest** [comment]
May I also ask if/how you tried these changes? I see that this does not build cleanly on Asteroid (libsystemd-daemon is not a thing, we use libsystemd instead which makes me question whether you ever tried to build asteroid against this)
EDIT: mce-qt5 is another example of .pc that is not provided on Asteroid. I'll revert your PR until you confirm that/how you tested it.

**Comment by neochapay** [comment]
I use you copy of lipsick for new version nemomobile with Qt 5.12. And just return changes to main source tree
`Do you plan to remove statefs from asteroid? (I'd be happy with this :)`
I remove statefs from nemo. If you get me list of components who require statefs i think i can help you.

**Comment by FlorentRevest** [comment]
Thanks for contributing back! It looks like the nemomobile build has quite few differences from the asteroidos build then. Maybe we should give it a closer look.

**Pull request merged**
